services:
  fenixdb:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: 'sbdatabase'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - fenix-storage:/var/lib/postgresql/data

volumes:
  fenix-storage: